baseurl = "http://unigornel.github.io/unigornel.org/"
languageCode = "en-us"
title = "Unigornel"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Unigornel"
	description = "A material design theme for documentations."

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/unigornel/unigornel"

	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "deep-purple"
    	accent  = "light-green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "Unigornel"


[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 0

[blackfriday]
	smartypants = true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
